name: ventas_mama_app
description: Aplicación de ventas para Mamá
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.0.6
  audioplayers: ^6.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/success.mp3
